require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/initializers/*'
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7.1

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

Rails/FilePath:
  Enabled: false

RSpec/LetSetup:
  Exclude:
    - 'spec/importers/billing_contracts_import_spec.rb'
    - 'spec/models/billing_contract_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/workers/calculate_bill_worker_spec.rb'

RSpec/UnspecifiedException:
  Exclude:
    - 'spec/controllers/account/admin/billing_contracts_imports_controller_spec.rb'

RSpec/MultipleExpectations:
  Max: 9

RSpec/ExampleLength:
  Max: 17

RSpec/FilePath:
  Enabled: false

RSpec/HookArgument:
  Exclude:
    - 'spec/support/controller_macros.rb'

RSpec/NestedGroups:
  Exclude:
    - 'spec/controllers/account/admin/billing_contracts_controller_spec.rb'

RSpec/NamedSubject:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 8

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Lint/ImplicitStringConcatenation:
  Exclude:

Style/BlockComments:
  Description: 'Do not use block comments.'
  StyleGuide: '#no-block-comments'
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'config/environments/*'

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/*'
    - 'app/importers/billing_contracts_import.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/*'

Metrics/AbcSize:
  Exclude:
    - 'app/importers/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'app/views/account/admin/billing_contracts/index.xlsx.axlsx'

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'app/importers/applications_import.rb'

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false
