require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/initializers/*'
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7.1

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

Rails/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 9

RSpec/ExampleLength:
  Max: 17

RSpec/FilePath:
  Enabled: false

RSpec/HookArgument:
  Exclude:
    - 'spec/support/controller_macros.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Style/BlockComments:
  Description: 'Do not use block comments.'
  StyleGuide: '#no-block-comments'
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'config/environments/*'

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/*'

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false
