version: '3.7'

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - localhost
      - elasticsearch

  localhost:
    image: postgres:12
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:7.6.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      ELASTICSEARCH_URL: "http://elasticsearch:9200"

volumes:
  bundle-volume:
  db-volume:
  elasticsearch-data:
